### ISSUE TITLE
store only shows the state, but no dispatch or commits

### ISSUE THREAD

**Issue by tomckiswe** [paleo/direct-vuex#1]
I love your approach of making the store typescript friendly. I am looking for a while how to do this.
If I make a store with 2 modules in, I can use the state directly, but the commits and dispatches are always empty. Is this expected for now?

**Comment by paleo** [comment]
Typing should be enabled on `dispatch` and `commit`! Have you appended ` as const` at the end of your module and store implementations?

I gave a [more complete example here](https://itnext.io/use-a-vuex-store-with-typing-in-typescript-without-decorators-or-boilerplate-57732d175ff3). If it still doesn't work, please give me a minimal sample of your code.

**Comment by tomckiswe** [comment]
Thank you, I forgot to export my module as const.
Another question, can you do something like mapState using typescript as well or do you call store.state.module.param from within a computed value? Is this reactive?

**Comment by paleo** [comment]
> can you do something like mapState using typescript as well

I did not plan to work on `mapState` because it is an old API designed for Vue 2 and I personally write my components with the [composition API](https://github.com/vuejs/composition-api). It is too early to know how to proceed with Vuex and Vue.js 3 yet: https://github.com/vuejs/composition-api/issues/8 .

> or do you call store.state.module.param from within a computed value?

This is what I do. Yes it is reactive. When you write `store.state` it just returns the real `state` from the underlying Vuex `store`.

And all the wrappers provided by direct-vuex for `dispatch`, `commit` and `getters` are really just wrappers that just call the real Vuex store.
